import Header from "@/Components/header";
import "./globals.css";
import PlayWindow from "@/Components/play-window/play-window";
import { Provider } from "react-redux";
import { store } from "@/store/store";

export const metadata = {
  title: "Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <Provider store={store}>
    <html lang="en">
      <body>
        <Header />
        {children}
        <PlayWindow />
      </body>
    </html>
    // </Provider>
  );
}
